# Setup

In [1]:
from os import path

__DIR__ = globals()['_dh'][0]
data_dir = path.relpath(path.join(__DIR__, "..", "_data"))

In [2]:
# Settings
_testing = True
_colab_install = True
_pm_log_sections = False

# Parameters
dataset = path.join(data_dir, "wiki", "20220301.en.1gb")
text_col = "text"

base_model = "bert-base-cased"
max_length = 128
vocab_size = 20_000

tokenize_params = dict(batched=True)
tokenizer_dir = path.join(data_dir, "pretrain", "tokenizer")

mlm_probability = 0.15
bert_config = dict()
training_args = dict(
    optim = "adamw_torch",
    num_train_epochs = 3,
    per_device_train_batch_size = 128,
    save_steps = 500,
)
model_dir = path.join(data_dir, "pretrain", "model")

## Process settings / parameters

In [3]:
from pprint import pprint

if _pm_log_sections:
    def pm_log_section(message):
        print(f"\n[===== {message} =====]\n")
else:
    def pm_log_section(message):
        return

if _colab_install:
    try:
        import google.colab
        
        colab_install_script = path.join(__DIR__, "..", "colab_install.sh")

        if not path.isfile(colab_install_script):
            script_url = "https://raw.githubusercontent.com/yenson-lau/pii-remediation/papermill/colab_install.sh"
            !wget $script_url -O $colab_install_script

        !bash $colab_install_script

    except ModuleNotFoundError:
        pass

if _testing:
    pm_log_section("Running on testing mode")
    dataset = path.join(data_dir, "wiki", "20220301.en.test")

    training_args = dict(
        optim = "adamw_torch",
        per_device_train_batch_size = 128,
        max_steps = 3,
        logging_steps = 1,
        evaluation_strategy = "steps",
    )

config = dict(
    dataset = dataset,
    text_col = text_col,

    base_model = base_model,
    max_length = max_length,
    vocab_size = vocab_size,

    tokenize_params = tokenize_params,
    tokenizer_dir = tokenizer_dir,

    mlm_probability = mlm_probability,
    bert_config = bert_config,
    training_args = training_args,
    model_dir = model_dir,
)

print(f"{'TESTING' if _testing else ''} Parameters:")
pprint(config, indent=2, sort_dicts=False)

TESTING Parameters:
{ 'dataset': '../_data/wiki/20220301.en.test',
  'text_col': 'text',
  'base_model': 'bert-base-cased',
  'max_length': 128,
  'vocab_size': 20000,
  'tokenize_params': {'batched': True},
  'tokenizer_dir': '../_data/pretrain/tokenizer',
  'mlm_probability': 0.15,
  'bert_config': {},
  'training_args': { 'optim': 'adamw_torch',
                     'per_device_train_batch_size': 128,
                     'max_steps': 3,
                     'logging_steps': 1,
                     'evaluation_strategy': 'steps'},
  'model_dir': '../_data/pretrain/model'}


# Load dataset

In [4]:
from datasets import Dataset, load_dataset

pm_log_section("Loading dataset")

ds_dir = dataset
dataset = dict()
for split in ["train", "val", "test"]:
    data_file = path.join(ds_dir, f"{split}_data.json")
    if not path.isfile(data_file):  data_file += ".gz"
    dataset[split] = load_dataset("json", data_files=data_file, field="data")["train"]

Using custom data configuration default-76618ebe809bedea
Reusing dataset json (/Users/yenson/.cache/huggingface/datasets/json/default-76618ebe809bedea/0.0.0/a3e658c4731e59120d44081ac10bf85dc7e1388126b92338344ce9661907f253)


  0%|          | 0/1 [00:00<?, ?it/s]

Using custom data configuration default-29cf15927ba28352
Reusing dataset json (/Users/yenson/.cache/huggingface/datasets/json/default-29cf15927ba28352/0.0.0/a3e658c4731e59120d44081ac10bf85dc7e1388126b92338344ce9661907f253)


  0%|          | 0/1 [00:00<?, ?it/s]

Using custom data configuration default-d702a3f3dcca03ab
Reusing dataset json (/Users/yenson/.cache/huggingface/datasets/json/default-d702a3f3dcca03ab/0.0.0/a3e658c4731e59120d44081ac10bf85dc7e1388126b92338344ce9661907f253)


  0%|          | 0/1 [00:00<?, ?it/s]

# Tokenization

In [5]:
from transformers import BertTokenizerFast

pm_log_section("Tokenizing")

In [6]:
tokenizer = (BertTokenizerFast
                .from_pretrained(base_model)
                .train_new_from_iterator(dataset["train"][text_col], vocab_size))
tokenizer.model_max_length = max_length

tokenizer.save_pretrained(tokenizer_dir);

In [7]:
tokenize_function = lambda ex: tokenizer(ex[text_col], truncation=True)

tokenized_dataset = {
    k: v.map(tokenize_function, remove_columns = list(v.features), **tokenize_params)
    for k, v in dataset.items()
}

  0%|          | 0/9 [00:00<?, ?ba/s]

  0%|          | 0/1 [00:00<?, ?ba/s]

  0%|          | 0/1 [00:00<?, ?ba/s]

# Train masked language model

In [8]:
import numpy as np
from transformers import (BertConfig,
                          BertForMaskedLM,
                          DataCollatorForLanguageModeling,
                          Trainer,
                          TrainingArguments)

pm_log_section("Training MLM")

data_collator = DataCollatorForLanguageModeling(tokenizer = tokenizer,
                                                mlm_probability = mlm_probability)

bert_config = BertConfig(vocab_size = tokenizer.vocab_size, **bert_config)
model = BertForMaskedLM(config = bert_config)

training_args = TrainingArguments(output_dir = model_dir,
                                  overwrite_output_dir = True,
                                  **training_args)

def compute_metrics(eval_preds):
    idxs0, idxs1 = np.where(eval_preds.label_ids!=-100)

    preds = np.argmax(eval_preds.predictions[idxs0, idxs1, :], axis=-1)
    labels = eval_preds.label_ids[idxs0, idxs1]

    acc = (preds==labels).sum()/len(preds)

    return {"accuracy": acc}

In [9]:
trainer = Trainer(model = model,
                  args = training_args,
                  data_collator = data_collator,
                  compute_metrics=compute_metrics,
                  train_dataset = tokenized_dataset["train"],
                  eval_dataset=tokenized_dataset["val"])

trainer.train()
trainer.save_model(model_dir)

max_steps is given, it will override any value given in num_train_epochs
***** Running training *****
  Num examples = 8788
  Num Epochs = 1
  Instantaneous batch size per device = 128
  Total train batch size (w. parallel, distributed & accumulation) = 128
  Gradient Accumulation steps = 1
  Total optimization steps = 3


  0%|          | 0/3 [00:00<?, ?it/s]

You're using a BertTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
***** Running Evaluation *****
  Num examples = 998
  Batch size = 8


{'loss': 10.087, 'learning_rate': 3.3333333333333335e-05, 'epoch': 0.01}


  0%|          | 0/125 [00:00<?, ?it/s]

[  0   0   0 ... 996 996 996] [11 19 20 ... 27 29 31]
{'eval_loss': 9.589364051818848, 'eval_accuracy': 0.03477878054149241, 'eval_runtime': 196.7673, 'eval_samples_per_second': 5.072, 'eval_steps_per_second': 0.635, 'epoch': 0.01}


***** Running Evaluation *****
  Num examples = 998
  Batch size = 8


{'loss': 9.5911, 'learning_rate': 1.6666666666666667e-05, 'epoch': 0.03}


  0%|          | 0/125 [00:00<?, ?it/s]

[  0   0   0 ... 996 996 996] [ 8 10 24 ... 25 27 35]
{'eval_loss': 9.396703720092773, 'eval_accuracy': 0.04782122905027933, 'eval_runtime': 192.98, 'eval_samples_per_second': 5.172, 'eval_steps_per_second': 0.648, 'epoch': 0.03}


***** Running Evaluation *****
  Num examples = 998
  Batch size = 8


{'loss': 9.3064, 'learning_rate': 0.0, 'epoch': 0.04}


  0%|          | 0/125 [00:00<?, ?it/s]

[  0   0   0 ... 996 996 997] [10 12 29 ... 19 31  8]
{'eval_loss': 9.32083797454834, 'eval_accuracy': 0.04348837209302325, 'eval_runtime': 177.5585, 'eval_samples_per_second': 5.621, 'eval_steps_per_second': 0.704, 'epoch': 0.04}




Training completed. Do not forget to share your model on huggingface.co/models =)


Saving model checkpoint to ../_data/pretrain/model
Configuration saved in ../_data/pretrain/model/config.json


{'train_runtime': 603.11, 'train_samples_per_second': 0.637, 'train_steps_per_second': 0.005, 'train_loss': 9.661534627278646, 'epoch': 0.04}


Model weights saved in ../_data/pretrain/model/pytorch_model.bin
